accounts/urls.py
from django.urls import path

from accounts.views import login_view, register_view, logout_view

app_name = 'account'


urlpatterns = [
    path('login/', login_view, name = 'login'),
    path('register/', register_view, name = 'register'),
    path('logout/', logout_view, name = 'logout'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import  settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name= 'home'),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls'))


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import post_index, post_detail, post_create, post_update, post_delete

app_name = 'post'


urlpatterns = [
    path('index/', post_index, name = 'index'),
    path('create/', post_create, name = 'create'),
    path('<slug:slug>/', post_detail, name='detail'),

    path('<slug:slug>/update/', post_update, name = 'update'),
    path('<slug:slug>/delete/', post_delete, name = 'delete'),
]

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.urls import  reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey('auth.User', default=1, verbose_name='Yazar', related_name= "posts", on_delete=models.SET_DEFAULT)
    title = models.CharField(max_length=120,verbose_name="Başlık")
    content  = RichTextField(verbose_name="İçerik")
    publisihing_date = models.DateTimeField(verbose_name="Yayınlanma Tarihi", auto_now_add=True)
    image = models.ImageField(null=True, blank=True)
    slug = models.SlugField(unique=True, editable=False, max_length=130)
    def __str__(self):
        return self.title


#return "/post/{}".format(self.id)

    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug': self.slug})

    def get_create_url(self):
        return reverse('post:create')

    def get_update_url(self):
        return reverse('post:update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('post:delete', kwargs={'slug': self.slug})

    def get_unique_slug(self):
        slug = slugify(self.title.replace('ı', 'i'))
        unique_slug = slug
        counter = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, counter)
            counter += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        return super(Post, self).save(*args, **kwargs)


    class Meta:
        ordering =['-publisihing_date']

class Comment(models.Model):

    post = models.ForeignKey('post.Post', related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=250, verbose_name='İsim')
    content = models.TextField(verbose_name='Yorum')
    created_date = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label = "Kullanıcı Adı")
    password = forms.CharField(max_length=100, label = "Password", widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user =authenticate(username = username, password = password)
            if not user:
                raise forms.ValidationError('Kullanıcı adını veya parolayı yanlış girdiniz!')
        return super(LoginForm, self).clean()


class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label = "Kullanıcı Adı")
    password1 = forms.CharField(max_length=100, label = "Password", widget = forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label = "Password Again", widget = forms.PasswordInput)

    class Meta:
        fields = [
            'username',
            'password1',
            'password2',
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Parolalar eşleşmiyor!')
        return password2

post/forms.py
from django import  forms
from .models import Post
from .models import Comment
from django_recaptcha.fields import ReCaptchaField


class PostForm(forms.ModelForm):
    captcha = ReCaptchaField()
    class Meta:
        model = Post
        fields =[
            'title',
            'content',
            'image',
        ]

class CommentForm(forms.ModelForm):
    captcha = ReCaptchaField()
    class Meta:
        model = Comment
        fields = [
            'name',
            'content',
        ]

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def home_view(request):
    if request.user.is_authenticated:
        context = {
            'isim': 'Ahmet'
        }
    else:
        context = {
            'isim': 'Misafir'
        }
    return render(request, 'home.html', context)

post/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, redirect, Http404
from .models import Post
from .forms import PostForm, CommentForm
from django.contrib import messages
from django.utils.text import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

# Create your views here.

def post_index(request):
    post_list = Post.objects.all()
    query = request.GET.get('q')
    if query:
        post_list = post_list.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)
        ).distinct()


    paginator = Paginator(post_list, 3)  # Show 25 contacts per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'post/index.html' , {'posts' : posts})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return HttpResponseRedirect (post.get_absolute_url())

    context = {
        'post' : post,
        'form' : form,
    }
    return render(request, 'post/detail.html', context)

#alternatif 1:
# if request.method == "POST":
      #  print(request.POST)
    #title = request.POST.get ('title')
    #content = request.POST.get ('content')
    #Post.objects.create(title= title, content= content)

#alternatif 2:
    # if request.method == "POST":
        #FORMDAN GELEN BİLGİLERİ KAYDET
        #form = PostForm(request.POST)
       # if form.is_valid():
           # form.save()
       # else:
            #FORMDAN GELEN BİLGİLERİ KULLANICIYA GÖSTER
           # form = PostForm()


def post_create(request):

    if not request.user.is_authenticated:
        raise Http404()


    form = PostForm (request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()


        messages.success(request, 'Başarılı bir şekilde oluşturuldu!', extra_tags= "mesaj-basarili")
        return HttpResponseRedirect (post.get_absolute_url())
    context = {
            'form': form,
        }
    return render(request, 'post/form.html', context)


def post_update(request, slug):

    if not request.user.is_authenticated:
        raise Http404()

    post = get_object_or_404(Post, slug=slug)
    form = PostForm (request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        messages.success(request, 'Başarılı bir şekilde güncellendi!')

        return HttpResponseRedirect (post.get_absolute_url())

    context = {
        'form': form,
    }
    return render(request, 'post/form.html', context)


def post_delete(request,slug):
    if not request.user.is_authenticated:
        raise Http404()

    post = get_object_or_404(Post, slug=slug)
    post.delete()

    return redirect('post:index')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Dersleri {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>



    {% include 'messages.html' %}

    {% include "header.html" %}

    {% block body %}

    {% endblock %}


    <script  src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top d-flex justify-content-end ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Django Dersleri</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <form class="d-flex" role="search " action="/index">
                <input class="form-control me-2" type="search" placeholder="Search"  name="q" aria-label="Search" value="{{ request.GET.q}}">
              </form>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Anasayfa</a>
        </li>
        {% if request.user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'post:create' %}">Yazı Ekle</a>
        </li>
        {% endif%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'post:index' %}">Blog</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="#">Hakkımda</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="#">İletişim</a>
        </li>

      </ul>
        <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-end">
                {% if not request.user.is_authenticated %}

                 <li class="nav-item">
                      <a class="nav-link" href="{% url 'account:login' %}">Giriş Yap</a>
                    </li>
                       <li class="nav-item">
                      <a class="nav-link" href="{% url 'account:register' %}">Kayıt Ol</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'account:logout' %}">Çıkış Yap</a>
                    </li>
                {% endif%}

            </ul>
        </div>

    </div>
  </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %} Anasayfa - {{ block.super }}{% endblock %}
{% block body%}
Hoşgeldiniz {{ request.user.get_full_name}} !
{% endblock %}

templates/messages.html
{% if messages %}
        {% for message in messages %}

        <div class="alert alert-success alert-dismissible fade show" role="alert">
{{ message }}  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
        {% endfor %}
{% endif %}

templates/post/comment.html
{% load crispy_forms_tags %}

<form method="POST">
    {% csrf_token %}

    {{ form|crispy }}

    <input type="submit" class="btn btn-primary" value="Yorum Ekle"/>



</form>

templates/post/detail.html
{% extends 'base.html' %}

{% block title %}Post Detail{% endblock %}

{% block body%}
    {% include 'messages.html'%}
                        <div class="container">
                           <div class="row">
                                <div class="col p-5">
                                    <div class="card" style="width: auto;">
                                      <div class="card-body">

                                          <p><small> {{ post.publisihing_date|timesince }} önce</small></p>
                                             {% if post.image %}

                                          <img src="{{ post.image.url }} " class = "img-fluid"/>
                                          {% endif %}

                                        <h5 class="card-title">{{ post.title }} </h5>
                                        <p class="card-text"> {{ post.content|safe|linebreaks}}</p>
                                        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">İncele</a>
                                                  {% if request.user.is_authenticated %}
                                        <a href="{{ post.get_update_url }}" class="btn btn-warning">Güncelle</a>
                                        <a href="{{ post.get_delete_url }}" class="btn btn-danger">Sil</a>
                                                  {% endif %}

                                      </div>
                                    </div>
                                    <br><hr>
                                    <h3>Yorum Ekle</h3>
                                    {% include 'post/comment.html' %}
                                    <hr>

                                    {% for comment in post.comments.all %}

                                    <h4>{{comment.name}} | <small>{{comment.created_date|timesince}} önce</small></h4>
                                    <p>{{comment.content|linebreaks}}</p>
                                    <hr>

                                    {% endfor %}
                                </div>
                            </div>
                        </div>
{% endblock %}

templates/post/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Form{% endblock %}

{% block body%}

<div class = "container">
    <div class="row">
        <div class="col-md-6 offset-3">
                 <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
        <h1>Form</h1>
        {{ form|crispy }}
        {{ form.media }}


            <input class ="btn btn-primary" type="submit" value="Gönder"/>
        </form>

        </div>
    </div>
</div>


{% endblock %}

templates/post/index.html
{% extends 'base.html' %}

{% block title %}Post List{% endblock %}

{% block body%}

    {#{% url 'detail' post.id %} #}
<div class="container">
<div class="row">
     <div class = "col px-5 ">
                {% for post in posts%}

                                        <div class="card mt-3 " style="width: auto;">
                                          <div class="card-body">
                                              <p><small> {{ post.publisihing_date|timesince }} önce</small></p>
                                              {% if post.image %}
                                               <img src="{{ post.image.url }} " class = "img-fluid"/>
                                                 {% endif %}
                                            <h5 class="card-title">{{ post.title }} </h5>
                                             <p>Yazar: <b>{{ post.user.get_full_name}}</b> </p>

                                            <p class="card-text"> {{ post.content|safe|linebreaks|truncatechars:150}}</p>
                                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">İncele</a>
                                                      {% if request.user.is_authenticated %}
                                            <a href="{{ post.get_update_url }}" class="btn btn-warning">Güncelle</a>
                                            <a href="{{ post.get_delete_url }}" class="btn btn-danger">Sil</a>
                                                      {% endif %}

                                          </div>
                                        </div>


                {% endfor%}
          </div>
            <div class="row row-cols-auto">

                            <div class="pagination">
                            <span class="step-links">
                                {% if posts.has_previous %}
                                    <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                                </span>

                                {% if posts.has_next %}
                                    <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                                {% endif %}
                            </span>
                        </div>
                </div>
                </div>
     </div>

{% endblock %}